[MaL] Revert include order changes
Changing include order causes an internal Eigen error:
Eigen/src/IterativeSolvers/InternalHeaderCheck.h:2:2: error:
   #error "Please include unsupported/Eigen/IterativeSolvers
   instead of including headers inside the src directory directly."

If possible the scaling include should be removed in the future.