ci(build-wheels): update macOS deployment target to 15.0
Fixing error in CI wheels build:
delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 12.0:
/private/var/folders/_w/j8dt52752156r6pv6qc95vyr0000gr/T/tmp66ow3b81/wheel/ogs/.dylibs/libomp.dylib has a minimum target of 15.0
Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=15.0' to update minimum supported macOS for this wheel.

BREAKING CHANGE: macOS wheels now require macOS 15.0 or higher, dropping support for older versions