[PL/Refl] Better compiler error messages
The usefulness of error messages is improved tremendously. Compare e.g.
(compiled with gcc):

old (close to useless)

../../ogs/ProcessLib/ThermoRichardsMechanics/ThermoRichardsMechanicsProcess.cpp:348:16:   required from here
../../ogs/ProcessLib/Reflection/ReflectionSetIPData.h:126:52: error: static assertion failed: The current member is not reflectable, so we expect it to be raw data.
  126 |         static_assert(detail::is_raw_data<Member>::value,
      |                                                    ^~~~~
../../ogs/ProcessLib/Reflection/ReflectionSetIPData.h:126:52: note: ‘std::integral_constant<bool, false>::value’ evaluates to false

vs. new and useful:

../../ogs/ProcessLib/ThermoRichardsMechanics/ThermoRichardsMechanicsProcess.cpp:348:16:   required from here
../../ogs/ProcessLib/Reflection/ReflectionSetIPData.h:126:31: error: static assertion failed: The current member is not reflectable, so we expect it to be raw data.
  126 |         static_assert(detail::is_raw_data_v<Member>,
      |                       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
../../ogs/ProcessLib/Reflection/ReflectionSetIPData.h:126:31: note: ‘ProcessLib::Reflection::detail::is_raw_data_v<ProcessLib::ThermoRichardsMechanics::MechanicalStrainData<2> >’ evaluates to false