[cmake] Don't use lld for Python module.
lld linker strips out PyInit_OpenGeoSys symbol which results in the
following runtime error:

ImportError: dynamic module does not define module export function (PyInit_OpenGeoSys)