build(tfel): Add missing include for MGIS
On mac non-petsc release build yields:
In file included from /Users/gitlab/builds/eLG42yR7z/0/ogs/build/release-all/Tests/CMakeFiles/testrunner.dir/Unity/unity_29_cxx.cxx:4:
1170
In file included from /Users/gitlab/builds/eLG42yR7z/0/ogs/ogs/Tests/MaterialLib/MFront/MFront.cpp:10:
1171
In file included from /Users/gitlab/builds/eLG42yR7z/0/ogs/ogs/MaterialLib/SolidModels/MFront/MFront.h:12:
1172
In file included from /Users/gitlab/builds/eLG42yR7z/0/ogs/ogs/MaterialLib/SolidModels/MFront/MFrontGeneric.h:12:
1173
In file included from /Users/gitlab/.cache/CPM/mgis/3bbe/include/MGIS/Behaviour/Behaviour.hxx:22:
1174
/Users/gitlab/.cache/CPM/mgis/3bbe/include/MGIS/Span.hxx:629:14: error: no member named 'terminate' in namespace 'std'; did you mean 'template'?
1175
  629 |         std::terminate();
1176
      |         ~~~~~^
1177
/Users/gitlab/.cache/CPM/mgis/3bbe/include/MGIS/Span.hxx:629:23: error: expected unqualified-id
1178
  629 |         std::terminate();
1179
      |                       ^
1180
2 errors generated.